dist: trusty
sudo: required
language: node_js
node_js:
  - "lts/*"
before_script: 
  - sudo useradd vagrant
  - sudo sh -c 'echo vagrant:vagrant | chgpasswd'
after_failure:
  - sudo cat /var/log/auth.log