dist: trusty
sudo: required
language: node_js
node_js:
  - "lts/*"
before_script: 
  - sudo useradd vagrant
  - sudo sh -c 'echo vagrant:vagrant | chgpasswd'
  - sudo cat /etc/passwd
  - sudo cat /var/log/auth.log
  